@echo off
echo Resetting Git origin...
git remote remove origin 2>nul
echo Initializing Git...
git init
echo Creating secure .gitignore and README...
echo node_modules> .gitignore
echo .env>> .gitignore
echo frontend/node_modules>> .gitignore
echo frontend/dist>> .gitignore
echo # Container Deployment Manager> README.md
echo Staging files...
git add .
echo Committing codebase...
git commit -m "Initialize project: Container Deployment Manager with secure Auth and Multi-tenancy"
echo Setting remote origin...
git remote add origin https://github.com/Aonikyadav/container-deployment-manager.git
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.
