@echo off
echo Initializing Git...
git init
echo Staging files...
git add .
echo Committing codebase...
git commit -m "Initialize project: Container Deployment Manager with secure Auth and Multi-tenancy"
echo Setting remote origin...
git remote add origin https://github.com/Aonikyadav/container-deployment-manager.git
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.
